# Docker Compose with explicit device mappings + volume mount
# This demonstrates the complete approach

version: '3.8'

services:
  dev-box-with-devices:
    image: ubuntu:22.04
    container_name: dev_box_with_devices
    privileged: true
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y util-linux coreutils &&
        echo 'Container ready - testing with device mappings...' &&
        /workspace/test-device-mount-vs-mapping.sh &&
        tail -f /dev/null
      "
    volumes:
      # Volume mount for file system access
      - /dev:/dev
      - .:/workspace
    devices:
      # Explicit device mappings for proper device access
      - /dev/nvme0n1:/dev/nvme0n1
      - /dev/nvme0n1p1:/dev/nvme0n1p1
      - /dev/nvme0n1p2:/dev/nvme0n1p2
      - /dev/nvme0n1p3:/dev/nvme0n1p3
      - /dev/nvme0n1p4:/dev/nvme0n1p4
      - /dev/nvme0n1p5:/dev/nvme0n1p5
      - /dev/nvme0n1p6:/dev/nvme0n1p6
      - /dev/nvme0n1p7:/dev/nvme0n1p7
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    restart: unless-stopped
