version: '3.8'

services:
  dev-box:
    image: wn1980/dev-box:arm64
    container_name: dev_box
    privileged: true
    network_mode: host
    pid: host
    ipc: host
    environment:
      - TZ=Asia/Bangkok
      - COMPOSE_BAKE=true
    volumes:
      - config:/home/ubuntu/.config
      - conda:/home/ubuntu/.conda
      - Codespaces:/workspace
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev:/dev
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/systemd:/run/systemd:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://localhost:8443/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  config:
  conda:
  Codespaces:
    external: true
