# Docker Compose with ONLY volume mount (no explicit device mappings)
# This demonstrates why volume mount alone is insufficient

version: '3.8'

services:
  dev-box-volume-only:
    image: ubuntu:22.04
    container_name: dev_box_volume_only
    privileged: true
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y util-linux coreutils &&
        echo 'Container ready - testing volume mount only...' &&
        /workspace/test-device-mount-vs-mapping.sh &&
        tail -f /dev/null
      "
    volumes:
      # ONLY volume mount - no explicit device mappings
      - /dev:/dev
      - .:/workspace
    # NOTE: No 'devices:' section here
    restart: unless-stopped
