version: '3'

services:
  vscode-ssh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscode-ssh-container
    volumes:
      - Codespaces:/home/dev/workspace
      # Device access for USB and hardware
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /media:/media
      - /mnt:/mnt
      # Uncomment to mount Docker socket if you need to use Docker inside the container
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${SSH_PORT:-2222}:22"
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Bangkok}
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # Resource limits for Conda environment
    mem_limit: ${MEM_LIMIT:-2g}
    mem_reservation: ${MEM_RESERVATION:-1g}
    cpus: ${CPU_LIMIT:-1.0}
    # mem_limit: 2g
    # cpus: '1.0'

volumes:
  Codespaces:
    external: true
